services:
  - type: web
    name: fbva-cadastro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application -w 2 --timeout 120 -b 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fbva-db
          property: connectionString
      - key: HTTPS
        value: "1"
      - key: FLASK_DEBUG
        value: "0"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: WA_PHONE_NUMBER_ID
        sync: false
      - key: WA_ACCESS_TOKEN
        sync: false
      - key: WA_WEBHOOK_VERIFY_TOKEN
        sync: false

databases:
  - name: fbva-db
    plan: free
    databaseName: fbva
    user: fbva_user
